### ISSUE TITLE
All metrics are strings

### ISSUE THREAD

**Issue by fenneh** [chrsblck/redisbeat#2]
Not sure the best way around this - A different elastic index template or to change the types before outputting.

Right now all the stats from redisbeat come out as strings, not helpful for a lot of Kibana visualisations 

For example - stats.used_memory

```
{
  "_index": "redisbeat-2016.04.14",
  "_type": "memory",
  "_id": "AVQVWpEkUJYMUCpuMgdo",
  "_score": null,
  "_source": {
    "@timestamp": "2016-04-14T15:18:56.529Z",
    "beat": {
      "hostname": "MYREDIS01",
      "name": "MYREDIS01"
    },
    "count": 1,
    "stats": {
      "mem_allocator": "jemalloc-3.6.0",
      "mem_fragmentation_ratio": "1.00",
      "used_memory": "2244184",
      "used_memory_human": "2.14M",
      "used_memory_lua": "92160",
      "used_memory_peak": "2190843384",
      "used_memory_peak_human": "2.04G",
      "used_memory_rss": "2243560"
    },
    "type": "memory"
  },
  "fields": {
    "@timestamp": [
      1460647136529
    ]
  },
  "sort": [
    1460647136529
  ]
}
```

This can be seen in a few places.

**Comment by chrsblck** [comment]
Agreed, there's not a great way to handle this programmatically. From the Redis INFO [docs](http://redis.io/commands/info):

> Notes
> Please note depending on the version of Redis some of the fields have been added or removed. A robust client application should therefore parse the result of this command by skipping unknown properties, and gracefully handle missing fields.
> Here is the description of fields for Redis >= 2.4.

This makes if pretty difficult to type each value coming through. 

That said, I've been doing a little work with elastic [metricbeat](https://github.com/elastic/beats/tree/master/metricbeat/module/redis) project,  which handles the types better, though doesn't support specific Redis versions.

**Comment by fenneh** [comment]
As you authored this @chrsblck I'm assuming you're using it!

Do you have a different index template to the one included which could be updated?

**Comment by chrsblck** [comment]
I have been using `metricbeat` for the last 2 weeks. I ran into the same issues you're having. It's possible to make the same changes we've made in `metricbeat`, that tie `redisbeat` to a specific Redis version...

**Comment by fenneh** [comment]
Just an FYI on this for anyone who runs into the same issue.

The redisbeat collector is now implemented into metricbeat, which is in alpha3 and will publish integers over strings. 

Closing this off :)
