### ISSUE TITLE
Make failed.

### ISSUE THREAD

**Issue by pjanzen** [chrsblck/redisbeat#4]
Hi,

I am trying to build redisbeat but fail to do so.

The error I am getting is:
go build
# github.com/chrsblck/redisbeat/beat

../src/github.com/chrsblck/redisbeat/beat/redisbeat.go:180: b.Events undefined (type _beat.Beat has no field or method Events)
scripts/Makefile:26: recipe for target 'build' failed
make: *_\* [build] Error 2

My enviroment looks like this:
pjanzen@pjanzen-VB ~/go_stuff/redisbeat $ lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 18 Sarah
Release:    18
Codename:   sarah
pjanzen@pjanzen-VB ~/go_stuff/redisbeat $ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pjanzen/go_stuff"
GORACE=""
GOROOT="/usr/lib/go-1.6"
GOTOOLDIR="/usr/lib/go-1.6/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

If you need any other information please let me know.

Regards,
Paul.

**Comment by chrsblck** [comment]
Thanks @pjanzen. I would also recommend having a look at the `metricbeat` Redis module, which I helped on in the beginning. 

https://github.com/elastic/beats/tree/master/metricbeat/module/redis
