### ISSUE TITLE
Building ERROR

### ISSUE THREAD

**Issue by ghost** [chrsblck/redisbeat#5]
Hello,

I have some trouble in building package with those sources:
I've tried with libbeat 1.3 and 5.0 

libbeat 1.3
go build
\# github.com/chrsblck/redisbeat/beat
/root/beats_work/src/github.com/chrsblck/redisbeat/beat/redisbeat.go:180: b.Publisher.Connect undefined (type *publisher.PublisherType has no field or method Connect)
make: *** [build] Error 2
#####################################################
libbeat 5.0
go build
\# _/var/tmp/redisbeat-master
./main.go:13: cannot use "github.com/chrsblck/redisbeat/beat".New() (type *"github.com/chrsblck/redisbeat/beat".Redisbeat) as type "github.com/elastic/beats/libbeat/beat".Creator in argument to "github.com/elastic/beats/libbeat/beat".Run
make: *** [build] Error 2

Could you help me or give an older release ?

Thanks a lot

**Comment by chrsblck** [comment]
@SpoYler1987 thanks for taking time to create this. I don't have much extra time in the upcoming weeks to integrate with the `libbeat` API changes. 

Would you be interested in taking a shot at it? If not, I should be able to take a look next week.

**Comment by ghost** [comment]
Sorry, i'he tried but i'm a beginner in git/go/beat dev .... and i built the package but i've got a panic and i don'ty know where so, if you could look at this it's could be great.

Thanks a lot.

**Comment by chrsblck** [comment]
@SpoYler1987 No worries, thanks.

Have a look at [metricbeat](https://github.com/elastic/beats/tree/master/metricbeat). I helped add the initial Redis integration.

**Comment by ghost** [comment]
@chrsblck Thanks for that work i'm playing with metricbeat.
